Repository sparta-USD/UNFT-django, pull requests merged in 2022-11, with the labels that each got.

#7 Feat : 회원가입, 로그인, 로그아웃 기능 구현 #2
  unft/migrations/0001_initial.py
  usd/settings.py
  usd/urls.py
  users/admin.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_usd.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement

#11 Feat : 회원가입 시 예외처리 사항 추가 #6
  users/admin.py
  users/serializers.py
  users/views.py
Labels: enhancement

#16 Feat: UNFT(작품) CRUD API 구현
  requirements.txt
  unft/migrations/0002_unft_hits.py
  unft/models.py
  unft/serializers.py
  unft/urls.py
  unft/views.py
  usd/settings.py
  usd/urls.py
Labels: enhancement

#13 Feat: front-end 연결을 위한 CORS 설정
  requirements.txt
  usd/settings.py
Labels: enhancement

#19 Feat: 메일링으로 Password 찾기/재설정, 전송되는 이메일 내용, 제목 수정 #1
  .gitignore
  usd/settings.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_usd.py
  users/models.py
  users/static/css/password_reset.css
  users/static/css/password_reset_confirm.css
  users/static/css/style.css
  users/static/images/logo.png
  users/templates/password_reset.html
  users/templates/password_reset_complete.html
  users/templates/password_reset_confirm.html
  users/templates/password_reset_done.html
  users/templates/password_reset_done_fail.html
  users/templates/password_reset_email.html
  users/templates/password_reset_subject.txt
  users/urls.py
  users/views.py
Labels: enhancement

#20 Feat: 로그인한 유저 Unft모델에 반영 및 Unft validate 처리
  unft/serializers.py
  unft/views.py
  usd/settings.py
  usd/urls.py
  users/admin.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_usd.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement

#23 Merge: 비밀번호 찾기, 재설정 기능
  .gitignore
  usd/settings.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_usd.py
  users/models.py
  users/static/css/password_reset.css
  users/static/css/password_reset_confirm.css
  users/static/css/style.css
  users/static/images/logo.png
  users/templates/password_reset.html
  users/templates/password_reset_complete.html
  users/templates/password_reset_confirm.html
  users/templates/password_reset_done.html
  users/templates/password_reset_done_fail.html
  users/templates/password_reset_email.html
  users/templates/password_reset_subject.txt
  users/urls.py
  users/views.py
Labels: enhancement

#24 Merge: 메인에 Unft(작품)앱 API 반영 반영
  unft/admin.py
  unft/migrations/0001_initial.py
  unft/migrations/0002_unft_hits.py
  unft/models.py
  unft/serializers.py
  unft/urls.py
  unft/views.py
  usd/urls.py
Labels: enhancement

#22 Feat: 거래/제안내역 CRUD 기능 완료 #5
  deal/admin.py
  deal/models.py
  deal/serializers.py
  deal/urls.py
  deal/views.py
  usd/urls.py
Labels: enhancement

#26 Feat: front-end 쿠키 사용을 위한 CORS 설정추가 #17
  usd/settings.py
Labels: enhancement

#28 Feat: 비밀번호 재설정 이메일 양식 수정
  deal/migrations/0001_initial.py
  unft/migrations/0001_initial.py
  users/migrations/0001_initial.py
  users/static/images/default_profile.png
  users/templates/password_reset_email.html
  users/views.py
Labels: enhancement

#30 Fix : 회원가입시 발생한 오류 체크 및 수정 완료
  deal/migrations/0001_initial.py
  unft/migrations/0002_alter_unft_result_image.py
  users/migrations/0002_alter_user_usd.py
  users/models.py
  users/serializers.py
Labels: bug

#32 Feat: 유저 프로필 조회 API 구현 #31
  unft/migrations/0002_alter_unft_result_image.py
  unft/views.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement

#33 Fix: 제안/거래내역 조회시 오류 수정
  deal/views.py
  unft/serializers.py
Labels: enhancement

#34 Feat: 비밀번호 찾기/재설정 화면 네비바 수정, 로그인버튼 동작
  deal/migrations/0001_initial.py
  unft/migrations/0001_initial.py
  unft/migrations/0002_alter_unft_result_image.py
  users/migrations/0001_initial.py
  users/templates/password_reset.html
  users/templates/password_reset_complete.html
  users/templates/password_reset_confirm.html
  users/templates/password_reset_done.html
  users/templates/password_reset_done_fail.html
  users/templates/password_reset_email.html
Labels: enhancement

#36 Fix: 제안 불가 오류 해결 #35
  deal/views.py
Labels: bug

#38 Feat: 거래 완료시 owner, usd필드 수정 #25
  deal/serializers.py
  deal/urls.py
  deal/views.py
Labels: enhancement

#41 Fix: List index out of range 에러 해결 #40
  unft/serializers.py
Labels: bug

#42 Fix: List index out of range 에러 해결 #40
  unft/serializers.py
Labels: bug

#44 Feat: 제안 승인시 다른제안들 처리 및 소지금액 처리 #43
  deal/views.py
Labels: enhancement

#45 U-NFT v1.0
  deal/views.py
Labels: enhancement

#46 Fix: 비밀번호 찾기 페이지 URL변경
  users/templates/password_reset.html
  users/templates/password_reset_complete.html
  users/templates/password_reset_confirm.html
  users/templates/password_reset_done.html
  users/templates/password_reset_done_fail.html
Labels: enhancement

#47 Docs: README.md 작성
  README.md
Labels: documentation
